[profile.default]
  remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/"
    ]
  src = 'contracts'
  out = 'out'
  libs = ['node_modules', 'lib']
  test = 'test'
  cache_path  = 'cache_forge'
  evm_version = "cancun"
  optimizer = true
  optimizer_runs = 200
  solc_version = "0.8.26"
  verbosity = 3

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[invariant]
  call_override = false
  depth = 100
  dictionary_weight = 80
  fail_on_revert = false
  include_push_bytes = true
  include_storage = true
  optimizer = false
  runs = 25

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 4
  wrap_comments = true
  ignore = [
    "contracts/Comp.sol",
    "contracts/GovernorBravo*.sol",
    "contracts/SafeMath.sol",
    "contracts/Timelock.sol",
    "contracts/test/GovernorAlpha.sol",
    "contracts/test/Multicall.sol"
  ]
