name: compound-governance

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci
  RPC_URL: ${{ secrets.RPC_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test        
      - name: Run Tests
        run: npm test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run Coverage
        run: npm run coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: build source
        run: npm run build
      - name: Run Lint
        run: npm run lint:check
